services:
  service:
    build:
      dockerfile: ./service.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
  ui:
    build:
      dockerfile: ./ui.Dockerfile
    depends_on:
      - service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BaseUrl=http://service:5000